"""add phone

Revision ID: 4d458c5ae1a4
Revises: 67c7adbaaffa
Create Date: 2025-02-16 22:43:34.915015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d458c5ae1a4'
down_revision = '67c7adbaaffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('number', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('number', sa.VARCHAR(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('phones')
    # ### end Alembic commands ###
