"""empty message

Revision ID: 6236bb1cf3eb
Revises: c53d3f728360
Create Date: 2025-02-19 14:28:10.368725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6236bb1cf3eb'
down_revision = 'c53d3f728360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('keywords', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo')
    # ### end Alembic commands ###
