"""empty message

Revision ID: 64bd42cab146
Revises: d3c9a83da7f6
Create Date: 2025-02-18 15:06:55.490523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bd42cab146'
down_revision = 'd3c9a83da7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=True))

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
