"""empty message

Revision ID: f8db84051613
Revises: 769e3fc00510
Create Date: 2025-02-18 16:54:59.088742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8db84051613'
down_revision = '769e3fc00510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=30), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=10000),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
